CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

												--------------------------------------
												-- RELATION: USERS                  --
												--------------------------------------
-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS users (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    password character varying,
    email character varying
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS users_pkey ON users(id uuid_ops);


												--------------------------------------
												-- RELATION: CONTENT-AUTHORIZATIONS --
												--------------------------------------
-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS content_authorizations (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false,
    type character varying NOT NULL,
    content_id uuid NOT NULL,
    CONSTRAINT content_authorizations_user_id_content_id_key UNIQUE (user_id, content_id)
);
COMMENT ON COLUMN content_authorizations.type IS 'The kind of authorization: ''for-life'', ''ephemeral'', etc';

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS content_authorizations_pkey ON content_authorizations(id uuid_ops);
CREATE UNIQUE INDEX IF NOT EXISTS content_authorizations_user_id_content_id_key ON content_authorizations(user_id uuid_ops,content_id uuid_ops);

												--------------------------------------
												-- RELATION: CONTENT                --
												--------------------------------------

-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS content (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    venue_id uuid NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    name character varying NOT NULL,
    uri character varying NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS content_pkey ON content(id uuid_ops);


												-----------------------------
												-- RELATION: PAYMENTS      --
												-----------------------------
-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS payments (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    amount integer NOT NULL,
    user_id character varying NOT NULL,
    source character varying NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS payments_pkey ON payments(id uuid_ops);

												-----------------------------
												-- RELATION: SUBSCRIPTIONS --
												-----------------------------
-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS subscriptions (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id uuid NOT NULL,
    subscribed boolean NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS subscriptions_pkey ON subscriptions(id uuid_ops);


												----------------------
												-- RELATION: VENUES --
												----------------------

-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS venues (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    city character varying NOT NULL,
    state character varying NOT NULL,
    zip character varying NOT NULL,
    address1 character varying NOT NULL,
    address2 character varying,
    name character varying NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS venues_pkey ON venues(id uuid_ops);

												-----------------------
												-- RELATION: CREDITS --
												-----------------------
												
-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS credits (
    id uuid PRIMARY KEY,
    credits smallint NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS credits_pkey ON credits(id uuid_ops);


